root: true
env:
  node: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:security/recommended-legacy
  - eslint:recommended
  - plugin:@typescript-eslint/all
  - airbnb-base
  - airbnb-typescript/base
  - plugin:unicorn/all
  - plugin:prettier/recommended
  - plugin:@eslint-community/eslint-comments/recommended
ignorePatterns:
  - dist
  - tests/deno
  - tests/bun/env.d.ts
  - tsup.config.ts
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project:
    - tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
  - security
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: .
rules:
  '@eslint-community/eslint-comments/no-unused-disable': error

  import/extensions: off
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  security/detect-object-injection: off

  '@typescript-eslint/max-params': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-type-alias': off
  '@typescript-eslint/prefer-readonly-parameter-types': off

  unicorn/no-null: off
  unicorn/prevent-abbreviations: off
  unicorn/prefer-string-replace-all: off
