git:
  commitMessage: 'chore: release v${version}'
  tagName: v${version}
npm:
  publish: false
plugins:
  '@release-it/conventional-changelog':
    preset: conventionalcommits
    infile: CHANGELOG.md
    ignoreRecommendedBump: true
hooks:
  'after:bump':
    pnpm lint && pnpm test:node && sed -i '' -e 's/${latestVersion}/${version}/g' README.md && git
    add -f dist README.md
